services:
  gazebo_noetic:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        PASSWORD: ${PASSWORD}
    image: gazebo_noetic
    container_name: gazebo_noetic
    # network_mode: host  # ← WSL2では推奨されないので削除
    ports:
      - "11311:11311"  # ROS master用（必要に応じて他も追加）
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - type: bind
        source: ../
        target: /home/${USERNAME}/workspace
      - type: bind
        source: ${HOME}/.ssh  # ~は使えないので${HOME}に
        target: /home/${USERNAME}/.ssh
        read_only: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    tty: true
    privileged: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

